CREATE TABLE IF NOT EXISTS `footer` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `footer_content` TEXT NOT NULL,
    `social_links` TEXT NULL,  
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
